{% set name = "polaris" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/polaris-lib/polaris-lib-{{ version }}.tar.gz
  sha256: 59ada1d2e54d8a6368820312583aafb64b877bb7da706a043230ef17afb26c36

build:
  entry_points:
    - polaris = polaris.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.10
    - tqdm
    - loguru
    - typer
    - pyyaml
    - pydantic >=2
    - pydantic-settings >=2
    - authlib
    - httpx
    - tenacity
    - filelock
    - numpy
    - pandas
    - scipy
    - scikit-learn
    - seaborn
    - datamol >=0.12
    - zarr
    - pyarrow

test:
  imports:
    - polaris
  commands:
    - pip check
    - polaris --help
  requires:
    - pip

about:
  summary: Client for the Polaris Hub.
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/polaris-hub/polaris

extra:
  recipe-maintainers:
    - hadim
    - cwognum
