{% set name = "polaris" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/polaris-lib/polaris_lib-{{ version }}.tar.gz
  sha256: 74892ab5de6d8eda4d43109c962a6c28000eef992ba11ed2d63750bcb2dd44bc

build:
  entry_points:
    - polaris = polaris.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - tqdm
    - loguru
    - typer
    - pyyaml
    - pydantic >=2
    - pydantic-settings >=2
    - authlib
    - httpx
    - tenacity
    - filelock
    - numpy <2
    - pandas
    - scipy
    - scikit-learn
    - seaborn
    - datamol >=0.12.1
    - fastpdb
    - zarr
    - pyarrow
    - fsspec
    - yaspin

test:
  commands:
    - polaris --help
    - python -c "import polaris; assert polaris.__version__ == '{{ version }}'"

about:
  summary: Client for the Polaris Hub.
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/polaris-hub/polaris

extra:
  recipe-maintainers:
    - Andrewq11
    - cwognum
