{% set name = "polaris" %}
{% set version = "0.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/polaris-lib/polaris_lib-{{ version }}.tar.gz
  sha256: 69af7d76b2d3d68371c006cf6a31cddc4466469a14e8ab6dbc535cfbdd607811

build:
  entry_points:
    - polaris = polaris.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - tqdm
    - loguru
    - typer
    - pyyaml
    - pydantic >=2
    - pydantic-settings >=2
    - authlib
    - httpx
    - tenacity
    - filelock
    - numpy <2
    - pandas
    - scipy
    - scikit-learn
    - seaborn
    - datamol >=0.12.1
    - fastpdb
    - zarr >=2,<3
    - pyarrow <18
    - fsspec
    - yaspin
    - typing-extensions >=4.12.0
    - boto3 >=1.35.0
    - pyroaring

test:
  requires:
    - python {{ python_min }}
  commands:
    - polaris --help
    - python -c "import polaris; assert polaris.__version__ == '{{ version }}'"

about:
  summary: Client for the Polaris Hub.
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/polaris-hub/polaris

extra:
  recipe-maintainers:
    - Andrewq11
    - cwognum
